"""
FamilyGenerator: Generate union-closed families for testing.
"""

import numpy as np
from typing import List, Set, Optional
import itertools
from .family import UnionClosedFamily


class FamilyGenerator:
    """
    Generate various types of union-closed families for testing and research.
    """

    @staticmethod
    def closure(sets: List[Set[int]], max_iterations: int = 1000) -> UnionClosedFamily:
        """
        Compute the union-closure of a collection of sets.

        Given a collection of sets, repeatedly add all pairwise unions
        until reaching a fixpoint (union-closed family).

        Args:
            sets: Initial collection of sets
            max_iterations: Maximum iterations to prevent infinite loops

        Returns:
            UnionClosedFamily containing the closure
        """
        current = {frozenset(s) for s in sets}

        for iteration in range(max_iterations):
            new_sets = set()
            current_list = list(current)

            for i, A in enumerate(current_list):
                for j in range(i, len(current_list)):
                    B = current_list[j]
                    union = A | B
                    if union not in current:
                        new_sets.add(union)

            if not new_sets:
                # Reached fixpoint
                break

            current.update(new_sets)

        return UnionClosedFamily([set(s) for s in current])

    @staticmethod
    def from_atoms(atoms: List[Set[int]]) -> UnionClosedFamily:
        """
        Generate union-closed family from atomic generators.

        The family consists of all possible unions of the atoms.

        Args:
            atoms: List of generating sets

        Returns:
            Union-closed family generated by atoms
        """
        all_sets = set()

        # Generate all subsets of atoms
        for r in range(len(atoms) + 1):
            for combo in itertools.combinations(atoms, r):
                if combo:
                    union = set().union(*combo)
                    all_sets.add(frozenset(union))
                else:
                    all_sets.add(frozenset())

        return UnionClosedFamily([set(s) for s in all_sets])

    @staticmethod
    def random_atoms(n: int, num_atoms: int, avg_size: float = None,
                     seed: Optional[int] = None) -> UnionClosedFamily:
        """
        Generate random union-closed family from random atoms.

        Args:
            n: Size of universe {1, 2, ..., n}
            num_atoms: Number of atomic generators
            avg_size: Average size of atoms (default: n/2)
            seed: Random seed

        Returns:
            Union-closed family
        """
        if seed is not None:
            np.random.seed(seed)

        if avg_size is None:
            avg_size = n / 2

        universe = set(range(1, n + 1))
        atoms = []

        for _ in range(num_atoms):
            # Sample size from Poisson-like distribution
            size = max(1, min(n, int(np.random.poisson(avg_size))))
            atom = set(np.random.choice(list(universe), size=size, replace=False))
            atoms.append(atom)

        return FamilyGenerator.from_atoms(atoms)

    @staticmethod
    def power_set(n: int) -> UnionClosedFamily:
        """
        Generate the full power set of {1, 2, ..., n}.

        Args:
            n: Size of universe

        Returns:
            Power set (trivially union-closed)
        """
        universe = list(range(1, n + 1))
        sets = []

        for r in range(n + 1):
            for combo in itertools.combinations(universe, r):
                sets.append(set(combo))

        return UnionClosedFamily(sets)

    @staticmethod
    def upward_closed(base_sets: List[Set[int]], universe: Set[int]) -> UnionClosedFamily:
        """
        Generate upward-closed family (if A ⊆ B and A ∈ F, then B ∈ F).

        Upward-closed families are automatically union-closed.

        Args:
            base_sets: Minimal elements of the family
            universe: Universal set

        Returns:
            Upward-closed (hence union-closed) family
        """
        family_sets = set()

        for base in base_sets:
            # Add all supersets of base within universe
            remaining = universe - base
            for r in range(len(remaining) + 1):
                for combo in itertools.combinations(remaining, r):
                    superset = base | set(combo)
                    family_sets.add(frozenset(superset))

        return UnionClosedFamily([set(s) for s in family_sets])

    @staticmethod
    def lattice(n: int) -> UnionClosedFamily:
        """
        Generate a lattice-based family (divisibility lattice, Boolean lattice, etc.).

        For simplicity, generates Boolean lattice on n elements.

        Args:
            n: Number of elements

        Returns:
            Lattice as union-closed family
        """
        # Boolean lattice = power set
        return FamilyGenerator.power_set(n)

    @staticmethod
    def erdos_renyi(n: int, p: float, seed: Optional[int] = None) -> UnionClosedFamily:
        """
        Generate random family using Erdős-Rényi model, then close it.

        Args:
            n: Size of universe
            p: Probability of including each element in each set
            seed: Random seed

        Returns:
            Union-closed family
        """
        if seed is not None:
            np.random.seed(seed)

        universe = set(range(1, n + 1))
        num_initial_sets = max(2, int(2 ** n * 0.1))  # 10% of power set

        initial_sets = []
        for _ in range(num_initial_sets):
            s = {elem for elem in universe if np.random.random() < p}
            if s:  # Non-empty
                initial_sets.append(s)

        if not initial_sets:
            initial_sets = [{1}]  # At least one set

        return FamilyGenerator.closure(initial_sets)

    @staticmethod
    def worst_case_candidate(n: int) -> UnionClosedFamily:
        """
        Generate a candidate family that might be a counterexample.

        Based on known hard cases: sparse families with balanced frequencies.

        Args:
            n: Size of universe

        Returns:
            Union-closed family designed to have low max frequency
        """
        # Strategy: Create atoms with disjoint support, then add unions
        # This tends to balance frequencies

        if n <= 2:
            return FamilyGenerator.power_set(n)

        # Partition universe into k roughly equal parts
        k = max(2, n // 2)
        universe = list(range(1, n + 1))
        partition_size = n // k

        atoms = []
        for i in range(k):
            start = i * partition_size
            end = start + partition_size if i < k - 1 else n
            atom = set(universe[start:end])
            if atom:
                atoms.append(atom)

        return FamilyGenerator.from_atoms(atoms)

    @staticmethod
    def challenging_family(n: int, seed: Optional[int] = None) -> UnionClosedFamily:
        """
        Generate a challenging family designed to test the conjecture.

        Combines multiple strategies to create hard instances.

        Args:
            n: Size of universe
            seed: Random seed

        Returns:
            Potentially challenging union-closed family
        """
        if seed is not None:
            np.random.seed(seed)

        # Use multiple small atoms with partial overlap
        num_atoms = max(2, n // 3)
        atom_size = max(2, n // 2)

        universe = list(range(1, n + 1))
        atoms = []

        for i in range(num_atoms):
            # Create atoms with controlled overlap
            if i == 0:
                atom = set(np.random.choice(universe, size=atom_size, replace=False))
            else:
                # Partial overlap with previous atom
                prev_atom = atoms[-1]
                overlap_size = max(1, atom_size // 3)
                overlap = set(np.random.choice(list(prev_atom),
                                              size=min(overlap_size, len(prev_atom)),
                                              replace=False))
                remaining = set(universe) - prev_atom
                if remaining:
                    new_elements = set(np.random.choice(list(remaining),
                                                        size=min(atom_size - len(overlap),
                                                                len(remaining)),
                                                        replace=False))
                    atom = overlap | new_elements
                else:
                    atom = overlap

            if atom:
                atoms.append(atom)

        return FamilyGenerator.from_atoms(atoms)


def generate_test_suite(num_families: int = 100, max_n: int = 10,
                        seed: Optional[int] = None) -> List[UnionClosedFamily]:
    """
    Generate a comprehensive test suite of union-closed families.

    Args:
        num_families: Number of families to generate
        max_n: Maximum universe size
        seed: Random seed

    Returns:
        List of diverse union-closed families
    """
    if seed is not None:
        np.random.seed(seed)

    families = []
    gen = FamilyGenerator()

    for i in range(num_families):
        n = np.random.randint(2, max_n + 1)
        method = np.random.choice([
            'random_atoms',
            'erdos_renyi',
            'worst_case',
            'challenging',
            'power_set'
        ], p=[0.4, 0.3, 0.1, 0.15, 0.05])

        if method == 'random_atoms':
            num_atoms = np.random.randint(2, min(n, 5))
            family = gen.random_atoms(n, num_atoms, seed=seed + i if seed else None)
        elif method == 'erdos_renyi':
            p = np.random.uniform(0.3, 0.7)
            family = gen.erdos_renyi(n, p, seed=seed + i if seed else None)
        elif method == 'worst_case':
            family = gen.worst_case_candidate(n)
        elif method == 'challenging':
            family = gen.challenging_family(n, seed=seed + i if seed else None)
        else:  # power_set
            family = gen.power_set(min(n, 5))  # Limit size for power set

        families.append(family)

    return families
